name: 'TODO IssueOps'
description: 'A GitHub Action that enables IssueOps by automatically creating, updating, and closing GitHub issues from TODO comments in your code.'
author: '@vesharma-dev'
inputs:
  token:
    description: 'The GitHub token to use for API operations'
    required: true
    default: ${{ github.token }}
  keywords:
    description: 'Comma-separated list of keywords to search for in comments'
    required: false
    default: 'TODO,FIXME'
  assignees:
    description: 'Comma-separated list of GitHub usernames to assign to new issues'
    required: false
  labels:
    description: 'Comma-separated list of labels to add to new issues'
    required: false
    default: 'todo-issueops'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: git-pull-request
  color: white
